apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  serviceAccountName: "{{SA_NAME}}"
  containers:
  - name: nginx
    image: nginx
  - name: ts-sidecar
    imagePullPolicy: Always
    image: "{{IMAGE_TAG}}"
    env:
      # Store the state in a k8s secret
    - name: KUBE_SECRET
      value: "{{KUBE_SECRET}}"
    - name: USERSPACE
      value: "false"
    - name: AUTH_KEY
      valueFrom:
        secretKeyRef:
          name: tailscale-auth
          key: AUTH_KEY
          optional: true
    securityContext:
      capabilities:
        add:
        - NET_ADMIN